### ISSUE TITLE
Cannot Install 0.20.0

### ISSUE THREAD

**Issue by han-tyumi** [mint-lang/asdf-mint#16]
```sh
❯ asdf install mint latest
∗ Downloading mint...
E: could not download mint 0.20.0
E: an error occurred downloading mint
```

The issue may be related to there being multiple `0.20.0` versions.

```sh
❯ asdf list-all mint
0.2.1
0.3.0
0.3.1
0.4.0
0.5.0
0.6.0
0.7.0
0.7.1
0.8.0
0.9.0
0.10.0
0.11.0
0.12.0
0.13.0
0.13.1
0.14.0
0.15.0
0.15.1
0.15.2
0.15.3
0.16.0
0.16.1
0.17.0
0.18.0
0.19.0
0.20.0
0.20.0
0.20.0
0.20.0
0.20.0
```

**Comment by gdotdesign** [comment]
I've updated the regexp that lists all versions https://github.com/mint-lang/asdf-mint/commit/2bd4ae38563a8b711787975504edc893e4ee4639 can you try again after updating the plugin `asdf plugin update mint` ?
